version: '3.8'

services:
  website-react:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/website/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    stdin_open: true
    tty: true
    networks:
      - website-network

  # Mock服务器（如果需要）
  mock-server:
    build:
      context: ./mock-server
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./mock-server:/app
    environment:
      - NODE_ENV=development
    networks:
      - website-network
    depends_on:
      - website-react

networks:
  website-network:
    driver: bridge
